// <auto-generated />
using System;
using CMMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMMS.Migrations
{
    [DbContext(typeof(CmmsContext))]
    [Migration("20260503133945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMMS.Models.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<DateTime?>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdAsignacion")
                        .HasName("PK__Asignaci__C3F7F966EA9C544A");

                    b.HasIndex("IdOrden");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Asignacion", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__677F38F5DF3AC508");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.DetalleOrden", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<decimal?>("CostoTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo_total");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdAsignacion")
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    b.Property<int?>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    b.Property<int?>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.HasKey("IdDetalle")
                        .HasName("PK__DetalleO__4F1332DEF6BC9943");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdOrden");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("DetalleOrden", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.Maquina", b =>
                {
                    b.Property<int>("IdMaquina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_maquina");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquina"));

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Serie")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serie");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdMaquina")
                        .HasName("PK__Maquina__9A2F321BB6683F5C");

                    b.HasIndex("IdCliente");

                    b.ToTable("Maquina", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.OrdenTrabajo", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdMaquina")
                        .HasColumnType("int")
                        .HasColumnName("id_maquina");

                    b.Property<int?>("IdTipoServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_servicio");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdOrden")
                        .HasName("PK__OrdenTra__DD5B8F333A5D2AC2");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMaquina");

                    b.HasIndex("IdTipoServicio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("OrdenTrabajo", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.Repuesto", b =>
                {
                    b.Property<int>("IdRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_repuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRepuesto"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("IdRepuesto")
                        .HasName("PK__Repuesto__9D97D13F363F5A72");

                    b.ToTable("Repuesto", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__6ABCB5E0384C04BE");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.SolicitudRepuesto", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("comentarios");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdAsignacion")
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    b.Property<int?>("IdRepuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_repuesto");

                    b.HasKey("IdSolicitud")
                        .HasName("PK__Solicitu__5C0C31F38ADB9FEE");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdRepuesto");

                    b.ToTable("SolicitudRepuesto", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.Tecnico", b =>
                {
                    b.Property<int>("IdTecnico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTecnico"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("especialidad");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdTecnico")
                        .HasName("PK__Tecnico__D550973730109881");

                    b.ToTable("Tecnico", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.TipoServicio", b =>
                {
                    b.Property<int>("IdTipoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_servicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoServicio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoServicio")
                        .HasName("PK__TipoServ__4227AB8E23A0DEC1");

                    b.ToTable("TipoServicio", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__4E3E04ADB3462BE5");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("CMMS.Models.Asignacion", b =>
                {
                    b.HasOne("CMMS.Models.OrdenTrabajo", "IdOrdenNavigation")
                        .WithMany("Asignacions")
                        .HasForeignKey("IdOrden")
                        .HasConstraintName("FK__Asignacio__id_or__4CA06362");

                    b.HasOne("CMMS.Models.Tecnico", "IdTecnicoNavigation")
                        .WithMany("Asignacions")
                        .HasForeignKey("IdTecnico")
                        .HasConstraintName("FK__Asignacio__id_te__4D94879B");

                    b.HasOne("CMMS.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Asignacions")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Asignacio__id_us__4E88ABD4");

                    b.Navigation("IdOrdenNavigation");

                    b.Navigation("IdTecnicoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CMMS.Models.DetalleOrden", b =>
                {
                    b.HasOne("CMMS.Models.Asignacion", "IdAsignacionNavigation")
                        .WithMany("DetalleOrdens")
                        .HasForeignKey("IdAsignacion")
                        .HasConstraintName("FK__DetalleOr__id_as__59063A47");

                    b.HasOne("CMMS.Models.OrdenTrabajo", "IdOrdenNavigation")
                        .WithMany("DetalleOrdens")
                        .HasForeignKey("IdOrden")
                        .HasConstraintName("FK__DetalleOr__id_or__5812160E");

                    b.HasOne("CMMS.Models.SolicitudRepuesto", "IdSolicitudNavigation")
                        .WithMany("DetalleOrdens")
                        .HasForeignKey("IdSolicitud")
                        .HasConstraintName("FK__DetalleOr__id_so__59FA5E80");

                    b.Navigation("IdAsignacionNavigation");

                    b.Navigation("IdOrdenNavigation");

                    b.Navigation("IdSolicitudNavigation");
                });

            modelBuilder.Entity("CMMS.Models.Maquina", b =>
                {
                    b.HasOne("CMMS.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Maquinas")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Maquina__id_clie__3E52440B");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("CMMS.Models.OrdenTrabajo", b =>
                {
                    b.HasOne("CMMS.Models.Cliente", "IdClienteNavigation")
                        .WithMany("OrdenTrabajos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__OrdenTrab__id_cl__440B1D61");

                    b.HasOne("CMMS.Models.Maquina", "IdMaquinaNavigation")
                        .WithMany("OrdenTrabajos")
                        .HasForeignKey("IdMaquina")
                        .HasConstraintName("FK__OrdenTrab__id_ma__44FF419A");

                    b.HasOne("CMMS.Models.TipoServicio", "IdTipoServicioNavigation")
                        .WithMany("OrdenTrabajos")
                        .HasForeignKey("IdTipoServicio")
                        .HasConstraintName("FK__OrdenTrab__id_ti__45F365D3");

                    b.HasOne("CMMS.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("OrdenTrabajos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__OrdenTrab__id_us__46E78A0C");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdMaquinaNavigation");

                    b.Navigation("IdTipoServicioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CMMS.Models.SolicitudRepuesto", b =>
                {
                    b.HasOne("CMMS.Models.Asignacion", "IdAsignacionNavigation")
                        .WithMany("SolicitudRepuestos")
                        .HasForeignKey("IdAsignacion")
                        .HasConstraintName("FK__Solicitud__id_as__5441852A");

                    b.HasOne("CMMS.Models.Repuesto", "IdRepuestoNavigation")
                        .WithMany("SolicitudRepuestos")
                        .HasForeignKey("IdRepuesto")
                        .HasConstraintName("FK__Solicitud__id_re__5535A963");

                    b.Navigation("IdAsignacionNavigation");

                    b.Navigation("IdRepuestoNavigation");
                });

            modelBuilder.Entity("CMMS.Models.Usuario", b =>
                {
                    b.HasOne("CMMS.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuario__id_rol__398D8EEE");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("CMMS.Models.Asignacion", b =>
                {
                    b.Navigation("DetalleOrdens");

                    b.Navigation("SolicitudRepuestos");
                });

            modelBuilder.Entity("CMMS.Models.Cliente", b =>
                {
                    b.Navigation("Maquinas");

                    b.Navigation("OrdenTrabajos");
                });

            modelBuilder.Entity("CMMS.Models.Maquina", b =>
                {
                    b.Navigation("OrdenTrabajos");
                });

            modelBuilder.Entity("CMMS.Models.OrdenTrabajo", b =>
                {
                    b.Navigation("Asignacions");

                    b.Navigation("DetalleOrdens");
                });

            modelBuilder.Entity("CMMS.Models.Repuesto", b =>
                {
                    b.Navigation("SolicitudRepuestos");
                });

            modelBuilder.Entity("CMMS.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CMMS.Models.SolicitudRepuesto", b =>
                {
                    b.Navigation("DetalleOrdens");
                });

            modelBuilder.Entity("CMMS.Models.Tecnico", b =>
                {
                    b.Navigation("Asignacions");
                });

            modelBuilder.Entity("CMMS.Models.TipoServicio", b =>
                {
                    b.Navigation("OrdenTrabajos");
                });

            modelBuilder.Entity("CMMS.Models.Usuario", b =>
                {
                    b.Navigation("Asignacions");

                    b.Navigation("OrdenTrabajos");
                });
#pragma warning restore 612, 618
        }
    }
}
